---
title: "sample_stats"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---



```{r}
pacman::p_load(
  "data.table",
  "ggplot2",
  "stringr",
  "tidyr",
  "dplyr",
  "ggtext",
  "pheatmap",
  "purrr",
  "here",
  "ggnewscale",
  "Biostrings",
  "rjson"
)
getwd()
source("src/constants.R")
source("src/themes.R")
source("src/utility.R")
```


```{r}
load_sequencing_stats <- function(path) {
  report <- fromJSON(file=path)
  return(report)
}
load_read_stats <- function(path, sample) {
  read_stats <- fread(path, header =  FALSE)[, Sample := sample] %>% dcast(Sample~V1, value.var = "V2")
  return(read_stats)
}
read_stats <- rbind(
  load_read_stats("/home/bio.aau.dk/lx38ll/dark-science/motif-identification/analysis/mfd02199/qc_reads/nanostat", "soil"),
  load_read_stats("/home/bio.aau.dk/lx38ll/dark-science/motif-identification/analysis/fecal2/qc_reads/nanostat", "fecal_complex"),
  load_read_stats("/home/bio.aau.dk/lx38ll/dark-science/motif-identification/analysis/AD/qc_reads/nanostat", "anaerobic_digestor")
)

load_assembly_stats <- function(path, sample){
  assembly_stats <- fread(path)[
      , .(
        n_contigs = .N,
        n50_contigs = N50(length)
      ) 
    ][, Sample := sample]
  return(assembly_stats)
}
assembly_stats <- rbind(
  load_assembly_stats("/home/bio.aau.dk/lx38ll/dark-science/motif-identification/analysis/mfd02199/mmlong2_lite/tmp/flye/40-polishing/filtered_stats.txt", "soil"),
  load_assembly_stats("/home/bio.aau.dk/lx38ll/dark-science/motif-identification/analysis/fecal2/mmlong2_lite/tmp/flye/40-polishing/filtered_stats.txt", "fecal_complex"),
  load_assembly_stats("/home/bio.aau.dk/lx38ll/dark-science/motif-identification/analysis/AD/mmlong2_lite/tmp/flye/40-polishing/filtered_stats.txt", "anaerobic_digestor"),
  load_assembly_stats("/projects/dark_science/nanomotif/nanomotif_article/data/PaPr00000216MP_nm_0.1.19/flye/assembly_info.txt", "fecal_simple")
)

```


```{r}
stats <- merge(assembly_stats, read_stats, by = "Sample", all = TRUE)[, gb_sequenced := as.numeric(number_of_bases) / 1e9]
select_stats <- stats[, c("Sample", "gb_sequenced", "n50_contigs", "n_contigs")]
```

